/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.37
 * Generated at: 2020-09-25 04:19:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views._16_005fmainForm;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class _02_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/Users/jangsang-og/Downloads/programming/eclipse/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp01/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1599713879510L));
    _jspx_dependants.put("jar:file:/Users/jangsang-og/Downloads/programming/eclipse/spring-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sp01/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/16_mainForm/include/includeFile.jsp", Long.valueOf(1600676204000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write("   \r\n");
      out.write("<!-- jstl -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- context path -->\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!-- jquery -->\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.5.1.js\"></script>\r\n");
      out.write("<!-- <script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js\"></script> -->\r\n");
      out.write("<!-- css -->\r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\">");
      out.write("      \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>메인</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t$(function() {\n");
      out.write("\t\tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' ==''){\n");
      out.write("\t\t\t$('#aLogin').show();\n");
      out.write("\t\t\t$('#aJoin').show();\n");
      out.write("\t\t\t$('#aLogout').hide();\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$('#aLogin').hide();\n");
      out.write("\t\t\t$('#aJoin').hide();\n");
      out.write("\t\t\t$('#aLogout').show();\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t//게시판목록\n");
      out.write("\t\t$('#aBoardList').on('click', function(e) {\n");
      out.write("\t\t\tif ('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' ==''){\n");
      out.write("\t\t\t\talert('로그인을 먼저 하세요!');\n");
      out.write("\t\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/board/list');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t//홈\n");
      out.write("\t\t$('#aHome').on('click', function(e) {\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/home');\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t//로그아웃\n");
      out.write("\t\t$('#aLogout').on('click', function(e) {\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\tvar result = confirm('로그아웃 하시겠습니까?');\n");
      out.write("\t\t\tif (result){\n");
      out.write("\t\t\t\t$(location).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/logout');\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t//내정보\n");
      out.write("\t\t$('#aMyinfo').on('click', function(e) {\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t$(this).attr('href', '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/myinfo');\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//로그인\n");
      out.write("\t\t$('#btnLogin').on('click', function(e) {\n");
      out.write("\t\t\t//아이디/패스워드 체크\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t$('#loginForm').attr('action','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/login');\n");
      out.write("\t\t\t$('#loginForm').attr('method','post');\n");
      out.write("\t\t\t$('#loginForm').submit();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//회원가입\n");
      out.write("\t\t$('#btnJoin').on('click', function(e) {\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t$(this).attr('href','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/join');\n");
      out.write("\t\t\t$('#myModal').modal('hide');\n");
      out.write("\t\t\t\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//로그인 취소\n");
      out.write("\t\t$('#btnLoginCancel').on('click', function(e) {\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t$('#loginModal').modal('hide');\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//회원가입 취소\n");
      out.write("\t\t$('#btnJoinCancel').on('click', function(e) {\n");
      out.write("\t\t\te.preventDefault(); //객체의 기본기능을 소멸\n");
      out.write("\t\t\t$('#joinModal').modal('hide');\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- Navbar -->\n");
      out.write("<nav class=\"navbar navbar-default\">\n");
      out.write("  <div class=\"container\">\n");
      out.write("    <div class=\"navbar-header\">\n");
      out.write("      <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>                        \n");
      out.write("      </button>\n");
      out.write("      <a class=\"navbar-brand\" href=\"\" id=\"aHome\" target=\"myframe\">홈</a>\n");
      out.write("      <a class=\"navbar-brand\" href=\"\" id=\"aBoardList\" target=\"myframe\">게시판</a>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("      <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("        <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#loginModal\" id=\"aLogin\">로그인</a></li>\n");
      out.write("        <li><a href=\"#\" data-toggle=\"modal\" data-target=\"#joinModal\" id=\"aJoin\">회원가입</a></li>\n");
      out.write("        <li><a href=\"\" id=\"aLogout\">로그아웃</a></li>\n");
      out.write("        <li><a href=\"\" id=\"aMyinfo\" target=\"myframe\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.userid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></li>\n");
      out.write("      </ul>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  <!-- 로그인 Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"loginModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog modal-sm\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("\t\t<div class=\"modal-header\">\n");
      out.write("\t \t\t<h4 class=\"modal-title\">로그인</h4>\n");
      out.write("\t    </div>\n");
      out.write("        <div class=\"modal-body\">\t    \n");
      out.write("\t\t\t<form id =\"loginForm\">\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"id\" type=\"text\" class=\"form-control\" name=\"id\" placeholder=\"id\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"pw\" placeholder=\"Password\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write(" \t\t<div class=\"modal-footer\">\n");
      out.write(" \t\t\t<a href=\"\"  class=\"btn btn-primary\" id=\"btnLogin\">로그인</a>\n");
      out.write(" \t\t\t<a href=\"\" class=\"btn btn-success\" id=\"btnLoginCancel\">취소</a>\n");
      out.write("\t\t</div>      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write("  <!-- 회원가입 Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"joinModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog modal-sm\">\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("\t\t<div class=\"modal-header\">\n");
      out.write("\t \t\t<h4 class=\"modal-title\">회원가입</h4>\n");
      out.write("\t    </div>\n");
      out.write("        <div class=\"modal-body\">\t    \n");
      out.write("\t\t\t<form id =\"joinForm\">\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"id\" type=\"text\" class=\"form-control\" name=\"id\" placeholder=\"id\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"pw\" placeholder=\"password\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"password\" type=\"email\" class=\"form-control\" name=\"email\" placeholder=\"email\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\t\t\t  \t<div class=\"input-group\">\n");
      out.write("\t\t\t    \t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-camera\"></i></span>\n");
      out.write("\t\t\t    \t<input id=\"password\" type=\"file\" class=\"form-control\" name=\"photofile\" placeholder=\"photo\">\n");
      out.write("\t\t\t  \t</div>\n");
      out.write("\n");
      out.write("\t\t\t</form>\n");
      out.write("\t\t</div>\n");
      out.write(" \t\t<div class=\"modal-footer\">\n");
      out.write(" \t\t\t<a href=\"\"  class=\"btn btn-primary\" id=\"btnJoin\">저장</a>\n");
      out.write(" \t\t\t<a href=\"\" class=\"btn btn-success\" id=\"btnJoinCancel\">취소</a>\n");
      out.write("\t\t</div>      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("  </div>\n");
      out.write("</nav>\t \n");
      out.write("<!-- First Container -->\n");
      out.write("<iframe name=\"myframe\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/form/home\">\n");
      out.write("\n");
      out.write("</iframe>\n");
      out.write("\n");
      out.write("<!-- Footer -->\n");
      out.write("<footer class=\"container-fluid bg-4 text-center\">\n");
      out.write("  <p>국제아카데미 <a href=\"http://www.gcacademy.co.kr\">www.gcacademy.co.kr</a></p> \n");
      out.write("</footer>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/16_mainForm/include/includeFile.jsp(7,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/16_mainForm/include/includeFile.jsp(7,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/16_mainForm/include/includeFile.jsp(7,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
